insert into public.reporting_connectors (
  id,
  name,
  source,
  destination,
  destination_table,
  status,
  owner,
  cadence,
  last_sync_at,
  next_sync_at,
  sla_minutes,
  freshness_minutes,
  records_24h,
  error_rate,
  latency_ms,
  tags
) values
  (
    'conn-shopify-orders',
    'Shopify Orders',
    'Airbyte Shopify',
    'bigquery',
    'analytics.shopify_orders',
    'healthy',
    'Revenue Ops',
    'Every 30 min',
    '2026-06-07T06:42:00Z',
    '2026-06-07T07:12:00Z',
    45,
    18,
    184203,
    0.001,
    812,
    array['orders', 'revenue', 'daily-close']
  ),
  (
    'conn-stripe-balance',
    'Stripe Balance Transactions',
    'Airbyte Stripe',
    'bigquery',
    'finance.stripe_balance_transactions',
    'degraded',
    'Finance Data',
    'Hourly',
    '2026-06-07T05:51:00Z',
    '2026-06-07T07:00:00Z',
    60,
    69,
    48122,
    0.027,
    1410,
    array['finance', 'settlement', 'reconciliation']
  ),
  (
    'conn-hubspot-companies',
    'HubSpot Companies',
    'Airbyte HubSpot',
    'supabase',
    'public.crm_companies',
    'healthy',
    'Growth',
    'Every 2 hours',
    '2026-06-07T05:33:00Z',
    '2026-06-07T07:33:00Z',
    150,
    87,
    9214,
    0,
    622,
    array['crm', 'accounts', 'sales']
  )
on conflict (id) do update set
  status = excluded.status,
  freshness_minutes = excluded.freshness_minutes,
  records_24h = excluded.records_24h,
  updated_at = now();
